"""Removed address field from Azienda model

Revision ID: 80999b0e6f55
Revises: 2dc617a056e2
Create Date: 2025-01-29 00:49:17.439283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80999b0e6f55'
down_revision = '2dc617a056e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aziende', schema=None) as batch_op:
        batch_op.drop_column('indirizzo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aziende', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indirizzo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
